export const ADD_COURSE_TITLE = 'ADD_COURSE_TITLE';
export const ADD_COURSE_LOGO = 'ADD_COURSE_LOGO';
export const ADD_COURSE_LESSONS = 'ADD_COURSE_LESSONS';
export const EDIT_COURSE_LESSON_NAME = 'EDIT_COURSE_LESSON_NAME';
export const DELETE_LESSON = 'DELETE_LESSON';